# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/sweet-miuicamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter arm64,$(TARGET_ARCH)),)

endif
