# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/sweet-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sweet-miuicamera/common


PRODUCT_PACKAGES += \
    android.hardware.camera.common@1.0 \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libgui-xiaomi \
    libhidltransport \
    libmicampostproc_client \
    vendor.xiaomi.hardware.campostproc@1.0 \
    libSNPE \
    vendor.qti.hardware.camera.device@1.0 \
    vendor.qti.hardware.camera.device@2.0 \
    vendor.qti.hardware.camera.device@3.5 \
    libmialgo_rfs_cdsp_skel \
    libsnpe_dsp_v65_domains_v2_skel \
    android.hardware.camera.provider@2.4-external \
    android.hardware.camera.provider@2.4-legacy \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-external-impl \
    camera.device@3.4-impl \
    camera.device@3.5-external-impl \
    camera.device@3.5-impl \
    camera.device@3.6-external-impl \
    libalRnBRT_GL_GBWRAPPER \
    libalsautils \
    libaoa \
    libarbitrarybytes \
    libarcdualcamsat \
    libarcsat \
    libcamera2ndk_vendor \
    libdeccfg \
    libeffects \
    libeffectsconfig \
    libipanat \
    liblearningmodule \
    libwebrtc_audio_preprocessing \
    libdisplayconfig.system.qti \
    MiuiCamera \
    android.hardware.camera.provider@2.4-service_64
